version: '3'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app 
    expose:
      - 8888
    env_file:
      - .env
  app2:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app 
    expose:
      - 8888
    env_file:
      - .env
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app1
      - app2
